Repository COSC481W-2025Winter/KeepOrDelete, pull requests merged in 2025-03, with the labels that each got.

#69 feat: previews for formatted docs
  package-lock.json
  package.json
  src/breadNbutter/keep_or_delete.js
  src/preload.js
  src/stylesheet.css
  test/previews.test.js
  test/res/small.docx
  test/res/small.pdf
  test/swipe.test.js
Labels: enhancement

#76 Add arrow key based file preview traversal + a tooltip
  src/breadNbutter/keep_or_delete.html
  src/breadNbutter/keep_or_delete.js
  src/stylesheet.css
  test/delete.test.js
  test/rename.test.js
  test/settings.test.js
  test/swipe.test.js
Labels: enhancement, Sprint-2

#79 AI Renaming Suggestions
  package-lock.json
  package.json
  src/AWS/api_template.js
  src/breadNbutter/keep_or_delete.html
  src/breadNbutter/keep_or_delete.js
  src/final_page.html
  src/index.js
  src/main_menu.html
  src/preload.js
  src/settings.html
  src/stylesheet.css
  src/view_file.html
  test/ai-rename.test.js
Labels: documentation, enhancement, Sprint-2

#77 feat: preview support for videos
  src/breadNbutter/keep_or_delete.js
  src/preload.js
  src/preview.js
  src/stylesheet.css
  test/previews.test.js
  test/res/small.mov
  test/res/small.mp4
Labels: enhancement, Sprint-2

#82 fixed: PDF-AI CSP conflicts
  src/breadNbutter/keep_or_delete.html
  src/index.js
Labels: bug

#85 More fixes for polish
  src/breadNbutter/Druski copy.jpg
  src/final_page.js
  src/main_menu.js
  src/main_page/keep_or_delete.html
  src/main_page/keep_or_delete.js
  src/main_page/trash.jpg
  src/preload.js
  src/settings.html
  src/stylesheet.css
  src/trash_page.js
  test/settings.test.js
Labels: enhancement

#86 refactor: preview test, no longer sleeps for fixed time
  package-lock.json
  package.json
  playwright.config.js
  test/previews.test.js
Labels: enhancement

#89 feat: scrolling text preview
  src/stylesheet.css
Labels: enhancement

#88 feat: isolated testing configuration
  src/index.js
  test/ai-rename.test.js
  test/delete.test.js
  test/final.page.test.js
  test/main.menu.test.js
  test/previews.test.js
  test/rename.test.js
  test/settings.test.js
  test/swipe.test.js
Labels: enhancement

#105 AI Enhancements / UI Rework
  package-lock.json
  package.json
  src/index.js
  src/main_page/keep_or_delete.html
  src/main_page/keep_or_delete.js
  src/preload.js
  src/stylesheet.css
  test/ai-rename.test.js
  test/rename.test.js
Labels: enhancement, Sprint-3

#108 Progress Bar Display
  src/main_page/keep_or_delete.html
  src/main_page/keep_or_delete.js
  src/stylesheet.css
Labels: enhancement, Sprint-3

#109 Minor Optimization and Fixes
  src/main_page/keep_or_delete.js
  src/preload.js
  src/view_file.html
  src/view_file.js
  test/ai-rename.test.js
  test/delete.test.js
  test/final.page.test.js
  test/main.menu.test.js
  test/previews.test.js
  test/rename.test.js
  test/settings.test.js
  test/swipe.test.js
Labels: enhancement
