Repository COSC481W-2025Winter/KeepOrDelete, pull requests merged in 2025-02, with the labels that each got.

#31 feat: plaintext file previews
  package-lock.json
  package.json
  src/breadNbutter/keep_or_delete.html
  src/breadNbutter/keep_or_delete.js
  src/main_menu.js
  src/preload.js
  src/stylesheet.css
Labels: enhancement, Sprint-1

#46 Setting's Page Testing
  .github/workflows/build.yml
  src/settings.js
  test/settings.test.js
Labels: Sprint-1

#44 Deletion test playwright
  package-lock.json
  package.json
  playwright.config.js
  src/breadNbutter/keep_or_delete.js
  test/delete.test.js
  test/main.menu.test.js
Labels: Sprint-1

#53 added: testing for file previews
  test/previews.test.js
Labels: enhancement, Sprint-1

#54 feat: improved file deletion UI interactions
  src/breadNbutter/keep_or_delete.js
Labels: enhancement

#58 added: deployment instructions
  DEPLOYMENT.md
Labels: documentation
