Repository COSC481W-2025Winter/KeepOrDelete, pull requests merged in 2025-04, with the labels that each got.

#110 Displaying a welcome message
  src/main_page/keep_or_delete.html
  src/main_page/keep_or_delete.js
  src/settings.js
  src/stylesheet.css
  test/ai-rename.test.js
  test/delete.test.js
  test/final.page.test.js
  test/main.menu.test.js
  test/previews.test.js
  test/rename.test.js
  test/swipe.test.js
Labels: enhancement, Sprint-3

#112 AI renaming for docx file types
  src/main_page/keep_or_delete.js
  src/preload.js
  src/preview.js
Labels: enhancement, Sprint-3

#115 Adding unit tests for progress bar
  test/progress.test.js
Labels: Sprint-3

#116 Logging image requests for AI renaming suggestions
  src/final_page.js
  src/main_page/keep_or_delete.js
  test/ai-rename.test.js
Labels: enhancement, Sprint-3

#117 Added alphabetical sorting for files
  src/main_page/keep_or_delete.html
  src/main_page/keep_or_delete.js
  src/stylesheet.css
  test/previews.test.js
  test/sorting.test.js
Labels: enhancement, Sprint-3

#111 Trash Page Subwindow Update
  src/main_page/keep_or_delete.html
  src/main_page/keep_or_delete.js
  src/stylesheet.css
  src/trash_page.html
  src/trash_page.js
  test/delete.test.js
  test/swipe.test.js
Labels: enhancement

#118 Fixed toggling UI elements for welcome page
  src/main_page/keep_or_delete.js
  src/stylesheet.css
  test/previews.test.js
Labels: bug

#122 refactor: finalize screen into modal
  src/main_page/keep_or_delete.html
  src/main_page/keep_or_delete.js
  src/stylesheet.css
  test/final.page.test.js
Labels: enhancement, Sprint-3

#126 refactor: modularize + styling
  docs/AWS/api_template.js
  eslint.config.js
  package-lock.json
  package.json
  src/final_page.html
  src/final_page.js
  src/main.js
  src/main_menu.html
  src/main_menu.js
  src/main_page/keep_or_delete.html
  src/main_page/keep_or_delete.js
  src/preload/preload.js
  src/preload/preview.js
  src/renderer/index.html
  src/renderer/res/edit.svg
  src/renderer/res/trash.jpg
  src/renderer/scripts/currentIndex.js
  src/renderer/scripts/fileObjects.js
  src/renderer/scripts/finalize.js
  src/renderer/scripts/inspect.js
  src/renderer/scripts/keep_or_delete.js
  src/renderer/scripts/llm.js
  src/renderer/scripts/progressBar.js
  src/renderer/scripts/rename.js
  src/renderer/scripts/settings.js
  src/renderer/scripts/sort.js
  src/renderer/scripts/swipe.js
  src/renderer/scripts/tooltip.js
  src/renderer/scripts/trashModal.js
  src/renderer/scripts/ui.js
  src/renderer/scripts/userAction.js
  src/renderer/stylesheet.css
  src/settings.html
  src/settings.js
  src/stylesheet.css
  src/trash_page.html
  src/trash_page.js
  src/view_file.html
  src/view_file.js
  test/ai-rename.test.js
  test/delete.test.js
  test/final.page.test.js
  test/main.menu.test.js
  test/previews.test.js
  test/progress.test.js
  test/rename.test.js
  test/settings.test.js
  test/sorting.test.js
  test/swipe.test.js
Labels: enhancement, Sprint-3

#113 docs: adds detailed installation instructions
  INSTALL.md
  installation_ex/1.png
  installation_ex/2.png
  installation_ex/3.png
  installation_ex/4.png
Labels: documentation, Sprint-3
